StylesPath = .vale/styles

MinAlertLevel = suggestion

Packages = proselint, write-good

[src/en/*.md]
BasedOnStyles = Vale, proselint, write-good

Vale.Repetition = YES
Vale.Spelling = YES

# Book writing needs some passive voice and hedging
write-good.Passive = suggestion
write-good.Weasel = suggestion
write-good.TooWordy = warning

[src/es/*.md]
BasedOnStyles = Vale
